# Generated by Django 6.0.7 on 2026-07-18 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True)),
                ('current_time', models.FloatField(default=0)),
                ('is_playing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.couple')),
            ],
        ),
    ]
