# Generated by Django 6.0.7 on 2026-07-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_watchroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchroom',
            name='is_playing',
        ),
        migrations.RemoveField(
            model_name='watchroom',
            name='updated_at',
        ),
    ]
