# Generated by Django 6.0.7 on 2026-07-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_watchroom_is_playing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchroom',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='watchroom',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
